# Generated by Django 2.2.17 on 2021-01-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_auto_20210117_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadeperfil',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil'),
            preserve_default=False,
        ),
    ]
