# Generated by Django 2.2.17 on 2021-01-17 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_auto_20210117_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('texto_personalidade', models.TextField(blank=True, null=True)),
                ('perfil_empreendedor', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalidadePerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil')),
                ('personalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.Personalidade')),
            ],
        ),
        migrations.AddField(
            model_name='habilidade',
            name='personalidade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perfil.Personalidade', blank=True, null=True),
            preserve_default=False,
        ),
    ]
