# Generated by Django 2.2.17 on 2021-01-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='static/respostas/imagens'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
